/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abner_practicecollect_ExampleUnitTest */

#ifndef _Included_com_abner_practicecollect_ExampleUnitTest
#define _Included_com_abner_practicecollect_ExampleUnitTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
